package com.example.vietforces.data.model

/**
 * Data models for the AI layer.
 *
 * These mirror the JSON structures described in require_app.md (§8.5–8.9, §9)
 * and are produced by [com.example.vietforces.data.remote.OpenAiClient].
 */

/**
 * A single mistake found by the AI (§8.6).
 */
data class AiMistake(
    val type: String,          // e.g. "missing_tone", "punctuation", "word_order"
    val text: String,          // the problematic fragment
    val suggestion: String,    // suggested correction
    val explanation: String    // short, friendly explanation
)

/**
 * Result of grading a short / open answer (§8.5, §9.1).
 * Used for fill-in-the-blank, sentence arrange and typed-word modes.
 */
data class AiGradingResult(
    val score: Int,                       // 0..10
    val isAcceptable: Boolean,            // is the answer acceptable in meaning?
    val feedback: String,                 // short comment
    val mistakes: List<AiMistake> = emptyList(),
    val suggestedAnswer: String? = null,
    val weaknessTags: List<String> = emptyList()
)

/**
 * Result of grading a short written paragraph (§6.2, §9.2).
 */
data class WritingFeedback(
    val score: Int,                       // 0..10
    val overallFeedback: String,
    val mistakes: List<AiMistake> = emptyList(),
    val correctedVersion: String,
    val weaknessTags: List<String> = emptyList()
)

/**
 * Natural mascot reaction generated by AI (§8.9, §9.3).
 */
data class MascotFeedback(
    val emotion: String,        // e.g. "happy", "encouraging", "thinking"
    val message: String,
    val shouldEncourage: Boolean = true
)

/**
 * One NPC turn in a roleplay conversation, enriched by the tutor layer.
 *
 *  - [reply] the in-character line shown as the NPC bubble.
 *  - [offTopic] true when the learner's last message was unrelated to the scenario
 *    (the NPC then gently steers back instead of guessing their intent).
 *  - [corrections] language mistakes found in the learner's last message
 *    (empty when it was already correct). Shown on demand under their bubble.
 *  - [suggestions] 1–2 simple Vietnamese lines the learner could say next
 *    (with an English gloss in parentheses), offered as tap-to-fill chips.
 *  - [goalsMet] which of the scenario's goal steps are satisfied so far.
 */
data class RoleplayTurn(
    val reply: String,
    val offTopic: Boolean = false,
    val corrections: List<AiMistake> = emptyList(),
    val suggestions: List<String> = emptyList(),
    val goalsMet: List<String> = emptyList()
)

/**
 * A detected learning weakness (§8.7).
 */
data class LearningWeakness(
    val type: String,
    val description: String,
    val recommendedPractice: String
)

/**
 * One step in the personalised learning path (§8.8).
 */
data class LearningPathItem(
    val title: String,
    val description: String,
    val targetWeakness: String,
    val recommendedMode: String,
    val priority: Int,
    val isCompleted: Boolean = false
)

/**
 * Full learning-path analysis returned by AI (§9.4).
 */
data class LearningPlan(
    val summary: String,
    val mainWeaknesses: List<LearningWeakness> = emptyList(),
    val learningPath: List<LearningPathItem> = emptyList()
)

/**
 * A topic the user can pick for the Writing Practice screen (§2).
 */
data class WritingTopic(
    val id: String,
    val title: String,
    val emoji: String,
    val hint: String,
    val suggestedMinWords: Int = 20
)

/**
 * One message in a roleplay conversation. [role] is "system", "user" or
 * "assistant" (matching the OpenAI chat API).
 */
data class ChatMessage(
    val role: String,
    val content: String
)

/**
 * Generic wrapper for any AI call so the UI can show loading / error / success
 * states and gracefully fall back when AI is unavailable (§12).
 */
sealed class AiCallResult<out T> {
    data class Success<T>(val data: T) : AiCallResult<T>()

    /**
     * @param message a user-friendly fallback message
     * @param isConfigError true when the key is missing / AI is disabled
     *        (so the UI can hint the user instead of looking like a crash)
     */
    data class Error(val message: String, val isConfigError: Boolean = false) :
        AiCallResult<Nothing>()
}
